version: "3"

services:
  db:
    image: postgres
    expose:
    - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./backups:/home/backups
    command: -p ${POSTGRES_PORT}
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    image: ttl_api_web
    container_name: ttl_api_web
    command: >
      sh -c "./manage.py migrate
      && ./manage.py collectstatic --noinput
      && gunicorn config.wsgi -b 0.0.0.0:${PORT}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/web
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: nginx_service
    volumes:
      - ./deploy:/etc/nginx/conf.d
      - ./.staticfiles:/static
    ports:
      - "100:100"
    depends_on:
      - web
