# Generated by Django 3.2.11 on 2022-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='studied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='studied at'),
        ),
    ]
