# Generated by Django 3.2.11 on 2022-02-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_bookmark'),
        ('article', '0004_auto_20220201_0217'),
    ]

    operations = [
    ]
