# Generated by Django 3.2.11 on 2022-02-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_merge_0003_bookmark_0004_auto_20220201_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('thumbs_up', 'thumbs_up'), ('heart', 'heart'), ('clap', 'clap'), ('lion', 'lion'), ('thinking', 'thinking'), ('smile', 'smile'), ('clover', 'clover'), ('eyes', 'eyes'), ('perfect', 'perfect'), ('bulb', 'bulb')], max_length=10, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='article.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedbacks',
            },
        ),
    ]
