# Generated by Django 3.2.11 on 2022-02-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20220209_2101'),
        ('article', '0008_alter_feedback_category'),
    ]

    operations = [
    ]
