# Generated by Django 3.2.11 on 2022-02-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_merge_20220211_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
