# Generated by Django 4.0.2 on 2022-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_study_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feedback_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
