# Generated by Django 3.2.12 on 2022-02-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmark_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
