# Generated by Django 3.2 on 2022-01-23 05:47

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.TextField(blank=True, null=True, verbose_name='introducing content'),
        ),
        migrations.AddField(
            model_name='user',
            name='repository',
            field=models.TextField(blank=True, null=True, verbose_name='refreshing github repository'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_recommended_mail',
            field=models.BooleanField(default=False, verbose_name='whether subscribe recommended mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
