# Generated by Django 3.2 on 2022-01-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_facebookaccount_instagramaccount_twitteraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='username',
            field=models.TextField(verbose_name='sns username'),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='username',
            field=models.TextField(verbose_name='sns username'),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='username',
            field=models.TextField(verbose_name='sns username'),
        ),
    ]
