# Generated by Django 3.2.11 on 2022-01-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220123_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='group name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'StudyGroup',
                'verbose_name_plural': 'StudyGroups',
                'db_table': 'study_groups',
            },
        ),
        migrations.CreateModel(
            name='UserStudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserStudyGroup',
                'verbose_name_plural': 'UserStudyGroup',
                'db_table': 'user_study_groups',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='study_groups',
            field=models.ManyToManyField(related_name='users', through='user.UserStudyGroup', to='user.StudyGroup'),
        ),
    ]
