# Generated by Django 3.2.11 on 2022-01-31 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_count', models.PositiveIntegerField(default=0)),
                ('write_count', models.PositiveIntegerField(default=0)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grasses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Grass',
                'verbose_name_plural': 'Grasses',
                'db_table': 'grasses',
            },
        ),
    ]
