# Generated by Django 4.0.2 on 2022-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_facebookaccount_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='velog_username',
            field=models.TextField(blank=True, null=True, verbose_name='velog username'),
        ),
    ]
