# Generated by Django 3.2.12 on 2022-02-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_velog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grass',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='grass',
            constraint=models.UniqueConstraint(fields=('user', 'created_at'), name='user_created_at_unique_index'),
        ),
    ]
