# Generated by Django 3.2.12 on 2022-02-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='twitteraccount',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_account',
            field=models.TextField(blank=True, null=True, verbose_name='facebook_account'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_account',
            field=models.TextField(blank=True, null=True, verbose_name='instagram_account'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_account',
            field=models.TextField(blank=True, null=True, verbose_name='twitter_account'),
        ),
        migrations.DeleteModel(
            name='FacebookAccount',
        ),
        migrations.DeleteModel(
            name='InstagramAccount',
        ),
        migrations.DeleteModel(
            name='TwitterAccount',
        ),
    ]
